Mob/storage caps
CenterForOpenScience/ember-osf-web pull request #1066
Opened 2020-09-18 19:43 UTC by fabmiz

- Ticket: []
- Feature flag: n/a

## Purpose

## Summary of Changes

## Side Effects

## QA Notes

2020-10-14 15:53 UTC, fabmiz commented on app/models/node-storage.ts
> +export default class NodeStorageModel extends OsfModel {
Add model unit tests, test computed props

2020-10-14 15:53 UTC, fabmiz commented on lib/osf-components/addon/components/file-browser/component.ts
> +    get moveAllowed(): boolean {
Rename to something more specific. `should...`;

2020-10-14 15:53 UTC, fabmiz commented on lib/osf-components/addon/components/file-browser/file-move-messages/component.ts
> +    @bool('project.links.relationships.parent') isChildNode!: boolean;
maybe `project.isRoot` for better readability

2020-10-14 15:53 UTC, fabmiz commented on lib/osf-components/addon/components/file-browser/file-move-messages/component.ts
> +    get selectedStorageStatus() {
```suggestion
    get selectedProjectStorageStatus() {
```

2020-10-14 15:53 UTC, fabmiz commented on app/guid-user/quickfiles/controller.ts
> +            if (e.status === '507') {
```suggestion
            if (e.status === 507) {
```

2020-10-14 15:53 UTC, fabmiz commented on mirage/factories/node-storage.ts
> +    }),
Add `NOT_CALCULATED` trait.

2020-10-14 16:10 UTC, futa-ikeda requested changes

2020-10-14 16:10 UTC, futa-ikeda commented on mirage/views/file.ts
> +    if (!node.public && node.storage.storageLimitStatus === StorageStatus.OVER_PRIVATE) {
use storage limit computeds here

2020-10-14 16:10 UTC, futa-ikeda commented on tests/acceptance/guid-user/quickfiles-test.ts
> +            const nodeStorage = server.create('node-storage');
Use `withStorage` trait on node

2020-10-14 16:10 UTC, futa-ikeda commented on tests/acceptance/guid-user/quickfiles-test.ts
> +            node.update({ storage: nodeStorage });
same here

2020-10-14 16:10 UTC, futa-ikeda commented on tests/acceptance/guid-user/quickfiles-test.ts
> +            node.update({ storage: nodeStorage });
and here

2020-10-14 16:10 UTC, futa-ikeda commented on tests/acceptance/guid-user/quickfiles-test.ts
> +            node.update({ storage: nodeStorage });
and here too

2020-10-15 15:14 UTC, fabmiz commented on app/models/node-storage.ts
> +export const TestCases: Record<'public' | 'private', Record<StorageStatus, { warning: boolean, error: boolean }>> = {
@futa-ikeda I don't think this is a good place for this const. It's not the model's concern and negatively affects readability. You could instead create a module that exports this const under `tests/fixtures/`

2020-10-15 19:10 UTC, merged