[ENG-2254] Fix link on branded navbar
CenterForOpenScience/ember-osf-web pull request #1067
Opened 2020-09-21 14:57 UTC by baylee-d

- Ticket: https://openscience.atlassian.net/browse/ENG-2254
- Feature flag: `N/A`

## Purpose

To fix the link route for the brand name on the navbar.

## Summary of Changes

- Added conditional to determine where the route should go to match the logo's link

## Side Effects

`N/A`

## QA Notes

This should fix the issue of the link going to the home route even for branded registries. The link should now take the user to the same route as the logo, which is the discover page.

2020-09-21 17:35 UTC, futa-ikeda approved these changes

2020-09-24 14:58 UTC, futa-ikeda requested changes
I think there's a leftover span + class?

2020-09-24 14:58 UTC, futa-ikeda commented on lib/registries/addon/components/registries-navbar/template.hbs
> +                <span local-class='Logo'></span>
Is this span needed (and by extension  `.Logo`)?

2020-09-24 15:06 UTC, futa-ikeda approved these changes

2020-09-24 15:06 UTC, fabmiz submitted a review, later dismissed
💯

2020-09-24 15:08 UTC, merged