Mob/moderation list view
CenterForOpenScience/ember-osf-web pull request #1073
Opened 2020-10-16 19:34 UTC by fabmiz

- Ticket: []
- Feature flag: n/a

## Purpose

## Summary of Changes

## Side Effects

## QA Notes

2020-10-21 18:49 UTC, fabmiz reviewed
overall great works 💯

2020-10-21 18:49 UTC, fabmiz commented on lib/registries/addon/components/registration-list/card/component.ts
> +const iconMap: Record<string, string> = {
Use `RegistrationReviewStates`
```suggestion
const iconMap: Record< RegistrationReviewStates, string> = {
```

2020-10-21 18:49 UTC, fabmiz commented on lib/registries/addon/components/registration-list/card/component.ts
> +    filterState: string;
```suggestion
    filterState: RegistrationReviewStates;
```

2020-10-21 18:49 UTC, fabmiz commented on lib/registries/addon/components/registration-list/card/template.hbs
> +            {{!-- TODO: Update this to be a link to the moderation overview page --}}
Address this ToDo item

2020-10-21 18:49 UTC, fabmiz commented on mirage/factories/review-action.ts
> +        reviewAction: ReviewActionModel;
Pluralize
```suggestion
        reviewActions: ReviewActionModel;
```

2020-10-21 18:49 UTC, fabmiz commented on translations/en-us.yml
> +        noActionsFound: 'Failed to load registration review history'
some consistency would be nice?
```suggestion
        moderator_action: '{action} {date} by {moderator}'
        no_actions_found: 'Failed to load registration review history'
```

2020-10-21 18:49 UTC, fabmiz commented on mirage/serializers/user.ts
> +        const retVal: SerializedRelationships<User> = {
minor: `retVal` is not a good variable name
```suggestion
        const serializedRelationships: SerializedRelationships<User> = {
```

2020-10-21 18:49 UTC, fabmiz commented on mirage/serializers/registration.ts
> +                    id: model.attrs,
why was this changed?
```suggestion
                    id: providerId,
```

2020-10-22 18:24 UTC, fabmiz commented on lib/registries/addon/components/registration-list/card/template.hbs
> +            {{!-- TODO: Update this to be a link to the moderation overview page --}}
Will get done once moderation overview page is in.

2020-11-13 17:04 UTC, futa-ikeda commented on lib/registries/addon/overview/-components/overview-header/component.ts
> +            this.toast.error(getApiErrorMessage(e));
Change this toast message to tell the user they need moderator permissions

2020-11-13 17:05 UTC, futa-ikeda commented on lib/registries/addon/overview/-components/overview-header/template.hbs
> +        {{#if (not (or @registration.archiving (eq @registration.reviewsState 'withdrawn')))}}
let's change this to a computed property

2020-11-13 17:07 UTC, futa-ikeda commented on lib/registries/addon/overview/controller.ts
> +    queryParams = ['viewMode'];
call this `mode`?

2020-11-13 17:08 UTC, futa-ikeda commented on lib/registries/addon/overview/template.hbs
> +        {{#if (or (eq this.registration.reviewsState 'withdrawn') this.registration.archiving)}}
make this computed as well?

2020-11-13 19:19 UTC, futa-ikeda requested changes

2020-11-13 19:19 UTC, futa-ikeda commented on translations/en-us.yml
> +            pendingWithdraw: 'Pending Withdraw'
```suggestion
            pendingWithdraw: 'Pending Withdrawal'
```

2020-11-16 20:47 UTC, futa-ikeda submitted a review, later dismissed

2020-11-16 21:58 UTC, futa-ikeda approved these changes

2020-11-16 21:58 UTC, adlius approved these changes

2020-11-16 22:40 UTC, merged