[WIP] Add tests, move files
CenterForOpenScience/ember-osf-web pull request #1104
Opened 2020-12-01 15:38 UTC by baylee-d

- Ticket: []
- Feature flag: n/a

## Purpose

To add tests for the `registration-list/card` component

## Summary of Changes

- Move file
- Add tests

## Side Effects

## QA Notes

2020-12-04 19:50 UTC, futa-ikeda requested changes
Couple of little things

2020-12-04 19:50 UTC, futa-ikeda commented on tests/integration/components/registries/registration-list/card/component-test.ts
> +/* tslint:disable:only-arrow-functions */
This tslint comment shouldn't be necessary

2020-12-04 19:50 UTC, futa-ikeda commented on tests/integration/components/registries/registration-list/card/component-test.ts
> +            @state={{this.manager.state}}
we can remove this.manager and just use `@state='pending'`

2020-12-08 16:47 UTC, futa-ikeda approved these changes

2020-12-08 16:47 UTC, futa-ikeda commented
Looks like some conflicts :/

2020-12-10 22:36 UTC, fabmiz commented
@baylee-d could you rebase pls?

2020-12-15 15:47 UTC, futa-ikeda approved these changes

2020-12-15 16:46 UTC, futa-ikeda commented
Some conflicts needing addressing here

2020-12-15 20:17 UTC, fabmiz commented on tests/integration/components/registries/registration-list/card/component-test.ts
> +        assert.dom('[data-test-registration-title-link]').exists();
I see value in checking if registration link  is correct and has `?mode=moderator`

2020-12-15 20:38 UTC, fabmiz reviewed
mostly nit-picky - was thinking for each state we could check the link (if any) and icon are as expected.

2020-12-15 20:38 UTC, fabmiz commented on tests/integration/components/registries/registration-list/card/component-test.ts
> +        assert.dom('[data-test-registration-title-link]').hasText(`${registration.title}`);
```suggestion
        assert.dom('[data-test-registration-title-link]').hasText(registration.title);
```

2020-12-15 20:38 UTC, fabmiz commented on tests/integration/components/registries/registration-list/card/component-test.ts
> +        assert.dom('[data-test-registration-list-card-title]').hasText(`${registration.title}`);
```suggestion
        assert.dom('[data-test-registration-list-card-title]').hasText(registration.title);
```

2020-12-15 20:38 UTC, fabmiz commented on tests/integration/components/registries/registration-list/card/component-test.ts
> +        }, 'withReviewActions');
maybe do this in a beforeEach? since both are doing the same thing?

2020-12-17 16:42 UTC, adlius approved these changes

2020-12-17 16:44 UTC, futa-ikeda approved these changes

2020-12-17 16:44 UTC, merged