Add registration list tests
CenterForOpenScience/ember-osf-web pull request #1105
Opened 2020-12-02 18:22 UTC by adlius

- Ticket: []
- Feature flag: n/a

## Purpose

## Summary of Changes

## Side Effects

## QA Notes

2020-12-03 15:00 UTC, fabmiz requested changes

2020-12-03 15:00 UTC, fabmiz commented on tests/integration/components/registries/registration-list/component-test.ts
> +    test('list renders and paginates', async function(assert) {
```suggestion
    test('list renders and paginates', async function(this: TestContext, assert) {
```

2020-12-03 15:00 UTC, fabmiz commented on tests/integration/components/registries/registration-list/component-test.ts
> +}
`import { TestContext } from 'ember-intl/test-support'`, adds `intl` to `ember-test-helpers`'s `TestContext`
```suggestion
```

2020-12-03 15:00 UTC, fabmiz commented on tests/integration/components/registries/registration-list/component-test.ts
> +        this.intl = this.owner.lookup('service:intl');
`setupIntl(hooks);` takes care of this
```suggestion
```

2020-12-03 15:00 UTC, fabmiz commented on tests/integration/components/registries/registration-list/component-test.ts
> +    test('list renders when no registration is available', async function(this: RegistrationListTestContext, assert) {
```suggestion
    test('list renders when no registration is available', async function(this: TestContext, assert) {
```

2020-12-03 20:47 UTC, fabmiz commented
@adlius lint errors

2020-12-04 20:27 UTC, fabmiz commented
@adlius conflicts 🤷‍♂️

2020-12-07 22:25 UTC, futa-ikeda submitted a review, later dismissed

2020-12-10 22:33 UTC, fabmiz commented
@adlius could you rebase pls?

2020-12-14 21:50 UTC, futa-ikeda approved these changes

2020-12-15 15:09 UTC, fabmiz approved these changes

2020-12-15 15:09 UTC, merged