Overview page acceptance tests
CenterForOpenScience/ember-osf-web pull request #1108
Opened 2020-12-04 11:57 UTC by adlius

- Ticket: []
- Feature flag: n/a

## Purpose

## Summary of Changes

## Side Effects

## QA Notes

2020-12-04 20:56 UTC, futa-ikeda requested changes
Looks great! Small suggestion with regards to the decision labels checking against a translated string, as opposed to a raw string.

2020-12-04 20:56 UTC, futa-ikeda commented on tests/engines/registries/acceptance/overview/moderator-mode-test.ts
> +            'Accept submission',
would these assertions be more robust if we checked against `t(registries.makeDecisionDropdown.acceptSubmission)`?

2020-12-04 20:56 UTC, futa-ikeda commented on tests/engines/registries/acceptance/overview/moderator-mode-test.ts
> +            'Reject submission',
... and checked against `t(registries.makeDecisionDropdown.rejectSubmission)`?

2020-12-04 20:56 UTC, futa-ikeda commented on tests/engines/registries/acceptance/overview/moderator-mode-test.ts
> +            'Force withdraw',
`t(registries.makeDecisionDropdown.forceWithdraw)`?

2020-12-04 20:56 UTC, futa-ikeda commented on tests/engines/registries/acceptance/overview/moderator-mode-test.ts
> +            'Accept withdrawal',
`t(registries.makeDecisionDropdown.acceptWithdrawal)`?

2020-12-04 20:56 UTC, futa-ikeda commented on tests/engines/registries/acceptance/overview/moderator-mode-test.ts
> +            'Reject withdrawal',
`t(registries.makeDecisionDropdown.rejectWithdrawal)`?

2020-12-04 20:56 UTC, futa-ikeda commented on tests/engines/registries/acceptance/overview/moderator-mode-test.ts
> +            'Force withdraw',
`t(registries.makeDecisionDropdown.forceWithdraw)`?

2020-12-04 20:56 UTC, futa-ikeda commented on tests/engines/registries/acceptance/overview/moderator-mode-test.ts
> +            'Force withdraw',
`t(registries.makeDecisionDropdown.forceWithdraw)`?

2020-12-04 20:56 UTC, futa-ikeda commented on tests/engines/registries/acceptance/overview/moderator-mode-test.ts
> +            'Force withdraw',
`t(registries.makeDecisionDropdown.forceWithdraw)`?

2020-12-07 14:02 UTC, adlius commented
> Looks great! Small suggestion with regards to the decision labels checking against a translated string, as opposed to a raw string.

The only problem is that the casing is different. In the template we use `humanize` instead of the translation strings.

2020-12-07 14:23 UTC, futa-ikeda commented
Ahh, I see now. I guess this goes back to the question of if we want to use sanitized keys/values passed from the backend as translations, but I think we can address that some other time

2020-12-07 14:23 UTC, futa-ikeda approved these changes

2020-12-07 15:04 UTC, fabmiz approved these changes
💯

2020-12-07 15:06 UTC, merged