[ENG-2617] Add DraftNode model
CenterForOpenScience/ember-osf-web pull request #1150
Opened 2021-03-02 18:22 UTC by fabmiz

- Ticket: [ENG-2617]
- Feature flag: n/a

## Purpose

Add DraftNode model

## Summary of Changes

## Side Effects

## QA Notes

2021-03-04 16:59 UTC, futa-ikeda requested changes

2021-03-04 16:59 UTC, futa-ikeda commented on mirage/serializers/file.ts
> +        if (model.targetId && model.targetId.id && model.kind === 'folder') {
Can move this kind==='folder' check inside of this first if-statement.
```if (model.targetId && model.targetId.id) {```

and move the 
```
if (model.kind === 'folder') { 
   returnValue.files = {
   ```

2021-03-04 16:59 UTC, futa-ikeda commented on mirage/serializers/file.ts
> +        if (model.targetId && model.targetId.id && model.kind === 'folder') {
Note: We check to see if the target exists here because quickfiles are associated to users, and have no target

2021-03-04 16:59 UTC, futa-ikeda commented on mirage/views/draft-registration.ts
> +            hasProject: true,
We could add the contributors from the `branchedFrom` here as an added bonus. Not important though.

2021-03-04 16:59 UTC, futa-ikeda commented on tests/engines/registries/acceptance/branded/new-test.ts
> +        // TODO: institutions, license, subjects, tags
Remove this todo

2021-03-08 22:07 UTC, futa-ikeda approved these changes
🚀

2021-03-09 22:13 UTC, futa-ikeda approved these changes
☄️

2021-03-10 14:25 UTC, adlius approved these changes

2021-03-10 15:17 UTC, merged