[ENG-2673] Show Add New for button for OSFRegistries
CenterForOpenScience/ember-osf-web pull request #1166
Opened 2021-03-16 15:36 UTC by futa-ikeda

- Ticket: [ENG-2673]
- Feature flag: n/a

## Purpose
- Allow users to create a draft registration to OSF Registries by using the Add New button

## Summary of Changes
- Show Add New button when looking at OSF Registries

## Side Effects
- NA

## QA Notes
- Add New button will be visible on `osf.io/registries/discover` route. This button will take users to `osf.io/registries/osf/new` and users should be able to submit to OSF registries from there

[ENG-2673]: https://openscience.atlassian.net/browse/ENG-2673

2021-03-16 20:03 UTC, brianjgeiger requested changes
One item.

2021-03-16 20:03 UTC, brianjgeiger commented on lib/registries/addon/components/registries-navbar/component.ts
>          if (!this.provider) {
Could probably just take out this whole branch

2021-03-16 20:07 UTC, brianjgeiger submitted a review, later dismissed

2021-03-16 20:09 UTC, fabmiz commented on lib/registries/addon/components/registries-navbar/component.ts
> +            return true;
maybe `defaultProviderId = 'osf'`

2021-03-17 14:10 UTC, brianjgeiger requested changes
One suggestion, since we're trying to get rid of magic strings.

2021-03-17 14:10 UTC, brianjgeiger commented on lib/registries/addon/components/registries-navbar/component.ts
> +    defaultProviderId: string = 'osf';
Should we just go all the way with this and put it in settings? It feels like a thing that would be in settings.

2021-03-18 12:37 UTC, brianjgeiger approved these changes
Nice

2021-03-18 14:36 UTC, fabmiz approved these changes
🥇

2021-03-18 16:00 UTC, merged