[My Registrations][ENG-528] Navbar links for My Registration page
CenterForOpenScience/ember-osf-web pull request #1171
Opened 2021-03-23 17:30 UTC by adlius

- Ticket: [ENG-528]
- Feature flag: n/a

## Purpose

Adding navbar link to "My Registrations" page. Also change the links into icons for mobile view.

## Summary of Changes

![Screenshot from 2021-03-23 13-23-34](https://user-images.githubusercontent.com/1566880/112190961-e5892080-8bdb-11eb-8314-85dd6d68fa40.png)
![Screenshot from 2021-03-23 13-23-48](https://user-images.githubusercontent.com/1566880/112190975-e8841100-8bdb-11eb-82dd-9940620cf24b.png)
![Screenshot from 2021-03-23 13-24-24](https://user-images.githubusercontent.com/1566880/112190994-ecb02e80-8bdb-11eb-8093-74d1b23737ba.png)
![Screenshot from 2021-03-23 13-24-08](https://user-images.githubusercontent.com/1566880/112191000-ee79f200-8bdb-11eb-881d-c90b935934f3.png)

2021-03-25 17:56 UTC, brianjgeiger requested changes
A couple of small things, plus a failing test.

2021-03-25 17:56 UTC, brianjgeiger commented on lib/osf-components/app/components/provider-metadata-editable/template.js
> +export { default } from 'osf-components/components/provider-metadata-editable/template';
This doesn't look like it belongs here.

2021-03-25 17:56 UTC, brianjgeiger commented on translations/en-us.yml
> +    my_registration: 'My Registration'
Should this be plural?

2021-03-30 15:24 UTC, futa-ikeda requested changes
Just a little copy-pasta that I see

2021-04-01 12:44 UTC, brianjgeiger submitted a review, later dismissed

2021-04-01 13:22 UTC, brianjgeiger commented
I'm not sure what's going on with the tests here, though.

2021-04-08 13:33 UTC, fabmiz requested changes
Please fix the tests and address accessibility concerns

2021-04-08 13:33 UTC, fabmiz commented on lib/registries/addon/components/registries-navbar/template.hbs
> +                    local-class='SecondaryNavLinkButton OnlyOnMobile'
Needs an aria-label attribute as there is no "discernible text" to indicate where this link point to.

2021-04-08 13:33 UTC, fabmiz commented on lib/registries/addon/components/registries-navbar/template.hbs
> +                    @route='registries.branded.new'
Ditto ☝🏽

2021-04-08 13:33 UTC, fabmiz commented on lib/registries/addon/components/registries-navbar/template.hbs
> +                local-class='SecondaryNavLinkButton OnlyOnMobile'
Ditto ☝🏽

2021-04-09 14:12 UTC, futa-ikeda approved these changes
🚀

2021-04-20 14:20 UTC, brianjgeiger approved these changes

2021-04-20 14:23 UTC, merged