[ENG-3035] Update Registration Cards
CenterForOpenScience/ember-osf-web pull request #1308
Opened 2021-09-28 14:00 UTC by chth0n1x

-   Ticket: https://openscience.atlassian.net/browse/ENG-3035
-   Feature flag: n/a

## Purpose

The purpose of this ticket was to add an update button to enable changes for versioning.

## Summary of Changes

## Screenshot(s)

## Side Effects

## QA Notes

2021-11-03 13:01 UTC, futa-ikeda requested changes
Had some feedback and a couple of questions

2021-11-03 15:19 UTC, chth0n1x commented on app/models/registration.ts
> +    @attr('boolean') createDoi?: boolean;
Got it, ok I just removed it.

2021-11-03 15:19 UTC, chth0n1x commented on app/models/registration.ts
> +    static reviewsState: string;
Ok, removed!

2021-11-03 15:30 UTC, chth0n1x commented on lib/osf-components/addon/components/node-card/component.ts
> +        if (registration.reviewsState !== 'accepted') {
Got it, logic now reads: `if (registration.reviewsState !== 'accepted' && registration.reviewsState !== 'embargo') {` on line 62.

2021-11-03 16:26 UTC, chth0n1x commented on lib/osf-components/addon/components/node-card/template.hbs
> +                                </BsButton>
Makes sense. Ok, it's removed!

2021-11-03 16:30 UTC, chth0n1x commented on lib/osf-components/addon/components/node-card/template.hbs
> +                                </BsButton>
Actually, would you like the whole menu item from line 97 to 112 deleted including the dropdown link?

2021-11-03 16:32 UTC, chth0n1x commented on lib/osf-components/addon/components/node-card/template.hbs
> +                {{/if}}
I was actually considering this. Would we like to set logic for the Approved updates/edits to show as 'Latest' update the first time the user logs in and sees or clicks on the Registration? 

Also yes the translation strings are updated locally, with changes pushed this morning.

2021-11-03 16:55 UTC, chth0n1x commented on lib/osf-components/addon/components/node-card/template.hbs
> +                                {{#if this.latestSchemaResponse}}
I agree. I just accepted the suggested code edit, thank you. I will begin testing it as well shortly.

2021-11-03 17:00 UTC, chth0n1x commented on lib/osf-components/addon/components/node-card/component.ts
> +            if (registration.reviewsState === 'accepted' || registration.reviewsState === 'embargo') {
Ok, making those changes now.

2021-11-03 18:41 UTC, chth0n1x commented on lib/osf-components/addon/components/node-card/component.ts
> +            if (registration.reviewsState === 'accepted' || registration.reviewsState === 'embargo') {
Ok, the code is now augmented `       if (!this.node?.userHasAdminPermission){
            return;
        }
        if (registration.reviewsState !== 'accepted' && registration.reviewsState !== 'embargo') {
            if (registration.revisionState !== 'approved') {
                return;
            }
        } else {
            try {
                const revisions = await registration.queryHasMany('schemaResponses');`

I can push changes shortly if that looks correct/best! If not, just let me know and I can update the logic.

2021-11-03 18:52 UTC, chth0n1x commented on lib/registries/addon/components/make-decision-dropdown/component.ts
> -    ActionableRevisionStates,
Of course, re-adding the missing import now.

2021-11-04 14:16 UTC, futa-ikeda commented on lib/osf-components/addon/components/node-card/component.ts
> +            if (registration.reviewsState === 'accepted' || registration.reviewsState === 'embargo') {
it's a little hard to read, but I think it looks right. Except the last else block you have, it is fetching revisions, it doesn't need to do that.

2021-11-08 14:39 UTC, chth0n1x commented on lib/osf-components/addon/components/node-card/template.hbs
> -                    {{@node.title}}
Yes it does. Thank you Futa.

2021-11-08 14:40 UTC, chth0n1x commented on lib/osf-components/addon/components/node-card/template.hbs
> -                    {{@node.title}}
I've readded the button now.

2021-11-08 14:40 UTC, chth0n1x commented on lib/osf-components/addon/components/node-card/template.hbs
> -                    {{@node.title}}
I've readded the link back now.

2021-11-08 15:41 UTC, chth0n1x commented on lib/osf-components/addon/components/node-card/template.hbs
> +                                {{#if this.latestSchemaResponse}}
Ok, the logic in place is ` {{else if this.shouldShowLinkToUpdate}}
                <Button
                    {{on 'click' (perform this.createNewSchemaResponse)}}
                    disabled={{this.createNewSchemaResponse.isRunning}}
                />`

2021-11-08 15:41 UTC, chth0n1x commented on lib/osf-components/addon/components/node-card/template.hbs
> +                                {{#if this.latestSchemaResponse}}
Will this resolve the second condition?

2021-11-09 16:08 UTC, futa-ikeda commented on lib/osf-components/addon/components/node-card/template.hbs
> +                {{else if (eq @node.revisionState 'unapproved')}}
```suggestion
                {{#if (eq @node.revisionState 'unapproved')}}
```

2021-11-09 16:10 UTC, futa-ikeda commented on lib/osf-components/addon/components/node-card/template.hbs
> +                             ......
```suggestion
```

2021-11-09 16:23 UTC, futa-ikeda commented on lib/osf-components/addon/components/node-card/template.hbs
> +                            {{/unless}}
```suggestion
```

2021-11-09 16:23 UTC, futa-ikeda commented on lib/osf-components/addon/components/node-card/template.hbs
> +                                {{#if this.latestSchemaResponse}}
I think the template file looks correct right now the way it is. We may want to tweak some of the logic in the `shouldShowUpdateButton` computed property, but we can update those in the component.ts file. We will also need to add a new computed property called `shouldShowLinkToUpdate` in the component.ts file so a link to the existing revision in progress is shown appropriately:

```
                        {{#if this.shouldShowUpdateButton}}
                            <Button
                              {{on 'click' (perform this.createNewSchemaResponse)}}
                              disabled={{this.createNewSchemaResponse.isRunning}}
                            />
                          {{else if this.shouldShowLinkToUpdate}}
                            <OsfLink
                                        data-analytics-name='Update'
                                        data-test-update-button='{{@node.id}}'
                                        @route='registries.edit-revision.index'
                                        @models={{array this.latestSchemaResponse.id}}
                                        >

                                        <Button
                                            local-class='RegistrationCard_update'
                                        >
                                            {{t 'node_card.update_button'}}
                                        </Button>
                                    </OsfLink>
                                {{/if}}
```

2021-11-09 16:36 UTC, futa-ikeda commented on lib/osf-components/addon/components/node-card/template.hbs
> +                {{/if}}
> Would we like to set logic for the Approved updates/edits to show as 'Latest' update the first time the user logs in and sees or clicks on the Registration?

We could, but I don't think it is necessary

2021-11-11 16:32 UTC, adlius commented
Closed in favor of #1346

2021-11-11 16:32 UTC, closed without merging