Add providers list to the leftnav when on registries file route
CenterForOpenScience/ember-osf-web pull request #1395
Opened 2022-02-02 21:24 UTC by futa-ikeda

-   Ticket: []
-   Feature flag: n/a

## Purpose
- Show file-providers for registries

## Summary of Changes
- Add element to show a registration's files provider on the registration overview page when you are on the registration's files route

## Screenshot(s)
![image](https://user-images.githubusercontent.com/51409893/152239414-9aef4a63-2a43-425c-907c-6ab4efe5852a.png)

## Side Effects

## QA Notes

2022-02-02 21:41 UTC, brianjgeiger requested changes
Overall, looks good. Just a few comments.

2022-02-02 21:41 UTC, brianjgeiger commented on lib/registries/addon/overview/template.hbs
> +                                    {{provider.name}}
I think we're going to have to make some way of converting the id to a display name. It should show as "OSF storage" not "osfstorage". Maybe we could use our translation service, and just pass that in as a key?

2022-02-02 21:41 UTC, brianjgeiger commented on lib/registries/addon/overview/template.hbs
> +                                                {{!-- region here --}}
You should be able to get this from the registration's region relationship, but you'll have to add it to the model, it looks like. There's no separate story ticket for this, but we could add one if you don't think it's appropriate for this PR.

2022-02-02 21:41 UTC, brianjgeiger commented on lib/registries/addon/overview/template.hbs
> +                                            <BsTooltip
Will we be able to style this to look like the mockups, or should we verify that everyone's cool with a standard tooltip?

2022-02-07 19:19 UTC, brianjgeiger approved these changes
Lookin' good.

2022-02-07 19:19 UTC, brianjgeiger commented on app/models/file.ts
> -    // TODO: In the future apiv2 may also need to support this pointing at nodes OR registrations
Look at you, fulfilling this TODO.

2022-02-07 19:25 UTC, futa-ikeda commented on app/models/file.ts
> -    // TODO: In the future apiv2 may also need to support this pointing at nodes OR registrations
Consider it TO-DONE 😄

2022-02-10 19:13 UTC, adlius commented on lib/registries/addon/overview/controller.ts
> +    @computed('router.currentRouteName')
Do we really need the `@computed` decorator here?

2022-02-10 21:09 UTC, merged