[ENG-3532][ENG-3535] Download and share files from file detail page
CenterForOpenScience/ember-osf-web pull request #1416
Opened 2022-02-28 16:03 UTC by brianjgeiger

-   Tickets: 
    - [ENG-3532](https://openscience.atlassian.net/browse/ENG-3532)
    - [ENG-3535](https://openscience.atlassian.net/browse/ENG-3535)
-   Feature flag: `ember_file_registration_detail_page`

## Purpose

Allow the file detail page to download and share files from the file action menu

## Summary of Changes

1. Refactor file actions menu into `<FileActionsMenu>`
2. Move `<SharingIcons>` out of registries engine and into main engine
3. Add `<FileActionsMenu>` to file detail and file list pages

## Screenshot(s)
<img width="1099" alt="Screen Shot 2022-02-28 at 10 48 16 AM" src="https://user-images.githubusercontent.com/6599111/156015901-e3a173c4-69e9-4523-adf5-2767282c4a81.png">

<img width="1173" alt="Screen Shot 2022-02-28 at 10 48 06 AM" src="https://user-images.githubusercontent.com/6599111/156015920-c8989f2f-e0ca-488b-beac-691366d72edd.png">

## Side Effects

No

## QA Notes

This does not fix any of the bugs with the file actions menu, including the mobile view and the accessibility problems. But once they're fixed, they should be fixed in both places.

2022-02-28 18:22 UTC, adlius commented on lib/osf-components/addon/components/file-actions-menu/template.hbs
> +            {{!-- use folder/file name for aria-label --}}
Is this comment still relevant?

2022-02-28 19:08 UTC, futa-ikeda requested changes
One old comment regarding a better aria-label for the share/download dropdown. It also looks like there will be some leftover classes that aren't being used on the file-detail page, so we can get rid of those in this PR.

2022-02-28 19:08 UTC, futa-ikeda commented on lib/osf-components/addon/components/file-actions-menu/template.hbs
> +            {{!-- use folder/file name for aria-label --}}
Can we pass the file name to this aria-label?

2022-02-28 19:48 UTC, futa-ikeda approved these changes

2022-03-01 18:06 UTC, adlius approved these changes

2022-03-01 18:06 UTC, merged