[ENG-3536] Add file-embed-menu to file-actions-menu
CenterForOpenScience/ember-osf-web pull request #1419
Opened 2022-03-03 19:23 UTC by brianjgeiger

-   Ticket: [ENG-3536](https://openscience.atlassian.net/browse/ENG-3536)
-   Feature flag: `ember_file_registration_detail_page`

## Purpose

Allow users to embed files into their own web pages

## Summary of Changes

1. Create `file-embed-menu` component
2. Add `file-embed-menu` component to `file-actions-menu`
3. Add translation strings
4. Test
5. Add render link to file links

## Screenshot(s)

<img width="642" alt="Screen Shot 2022-03-02 at 2 18 30 PM" src="https://user-images.githubusercontent.com/6599111/156637366-04ff0384-5c1e-435e-8553-8d0c765efcdc.png">

## Side Effects

This will also put the embed on the file list screen.

## QA Notes

This does not fix the accessibility problem with the menu's no-nested-interactive problem, nor any styling issues that may be happening in mobile.

2022-03-04 14:54 UTC, chth0n1x commented on lib/osf-components/addon/components/file-embed-menu/component.ts
> +        position:relative;
Hi Brian, will returning CSS result in external style sheets' formatting being overwritten?

2022-03-04 15:41 UTC, brianjgeiger commented on lib/osf-components/addon/components/file-embed-menu/component.ts
> +<link href="${mfrStaticUrl}/css/mfr.css" media="all" rel="stylesheet">
So the purpose of these blocks of text is that they will be copied to the user's clipboard, and the end user will paste them into their own web page to embed an mfr block on their page. Nothing in these blocks will go onto our site.

2022-03-07 14:16 UTC, futa-ikeda requested changes
Looks great! Just a couple minor optimizations that I would suggest

2022-03-07 14:58 UTC, brianjgeiger commented on lib/osf-components/addon/components/file-embed-menu/component.ts
> +</script>`.trim().replace(/^\s{12}/mg, ''));
This was just taken from what we had already in quickfiles. But, checking what it does, it looks like it should be unnecessary with the way I've created the string. It was trimming off three tabs worth of whitespace from the beginning of the string.

2022-03-07 16:47 UTC, futa-ikeda approved these changes
🗄️ 💨

2022-03-16 05:46 UTC, merged