[ENG-3724] Delete multiple files
CenterForOpenScience/ember-osf-web pull request #1498
Opened 2022-05-25 15:24 UTC by adlius

-   Ticket: []
-   Feature flag: n/a

## Purpose

## Summary of Changes

## Screenshot(s)

## Side Effects

## QA Notes

2022-05-25 17:44 UTC, futa-ikeda requested changes

2022-05-25 17:44 UTC, futa-ikeda commented on lib/osf-components/addon/components/file-browser/delete-file-modal/component.ts
> +export default class FileBrowser extends Component<Args> {
```suggestion
export default class DeleteFileModal extends Component<Args> {
```

2022-05-25 17:44 UTC, futa-ikeda commented on lib/osf-components/addon/components/file-browser/delete-file-modal/template.hbs
> +                            @layout='fake-link'
This guy needs an aria-label

2022-05-25 17:44 UTC, futa-ikeda commented on lib/osf-components/addon/components/file-browser/template.hbs
> +                <FileBrowser::DeleteFileModal @items={{@manager.selectedFiles}} @reload={{@manager.reload}} />
There should be a permission check here

2022-05-25 17:44 UTC, futa-ikeda commented on lib/osf-components/addon/components/file-browser/delete-file-modal/template.hbs
> +            {{on 'click' dialog.close}}
When a user hits cancel, should we stop the delete tasks that are currently in progress? Also needs one more indent level

2022-05-25 19:42 UTC, brianjgeiger requested changes
Just one thing from me.

2022-05-25 19:42 UTC, brianjgeiger commented on lib/osf-components/addon/components/file-browser/delete-file-modal/template.hbs
> +                        >
This should not be an active button if the retryDelete task is running. It should probably be a pulsed spinner with no clickability.

2022-05-26 18:40 UTC, brianjgeiger approved these changes
My stuff is cleared up. This is good once Futa is happy.

2022-05-26 19:21 UTC, futa-ikeda approved these changes

2022-05-26 19:22 UTC, merged