[ENG-3729] Add file checkout icon and logic;
CenterForOpenScience/ember-osf-web pull request #1502
Opened 2022-05-26 18:13 UTC by futa-ikeda

-   Ticket: [ENG-3729]
-   Feature flag: n/a

## Purpose
- Add checkout file icon and logic to show/hide stuff based on it

## Summary of Changes
- Add isCheckedOut property for osf-storage-files
- Add checkedOut logic for showing/hiding file operations (hide rename, delete, move)
## Screenshot(s)
- hover lock icon
![image](https://user-images.githubusercontent.com/51409893/170550118-3441a8b3-1e93-4919-9a27-dc2bc1054e25.png)
- file action dropdown options
![image](https://user-images.githubusercontent.com/51409893/170550205-02e0667d-f4ec-424e-917b-ab603ac2454e.png)

## Side Effects

## QA Notes

2022-05-26 18:20 UTC, brianjgeiger requested changes
One general comment: I believe the person who checked out the file can still make changes to it, so you might need to verify that the current user is not the checked out user for your logic. It would be good to still show the icon, I think, but the file shouldn't be considered read-only for the checking-out user, and the tooltip would read differently. You can verify how this functions on Prod/test in case I'm talkin' crazy.

2022-05-26 18:46 UTC, adlius commented on app/packages/files/osf-storage-file.ts
> +
A nitpick but can we use call the super class' `currentUserCanDelete` here?

2022-05-26 19:27 UTC, brianjgeiger commented
Sorry about the merge conflict.

2022-05-26 19:50 UTC, futa-ikeda commented
> One general comment: I believe the person who checked out the file can still make changes to it, so you might need to verify that the current user is not the checked out user for your logic. It would be good to still show the icon, I think, but the file shouldn't be considered read-only for the checking-out user, and the tooltip would read differently. You can verify how this functions on Prod/test in case I'm talkin' crazy.
> 
> Edit: You could _probably_ skip the icon if it's the current user to simplify things. There's no way for them to check it in on this page.

It looks like current behavior is that checked files can't be renamed, moved, or deleted. In the legacy file-detail page, it can be edited by the person who checked out the file (a feature we are not supporting going forward), and a new version can be made doing a drag+drop as long as the person adding it is the person who has checked out the file

2022-05-26 19:54 UTC, brianjgeiger approved these changes

2022-05-27 16:34 UTC, adlius approved these changes

2022-05-27 16:58 UTC, merged