[ENG-3911] New feature popover
CenterForOpenScience/ember-osf-web pull request #1571
Opened 2022-07-11 19:44 UTC by adlius

-   Ticket: []
-   Feature flag: n/a

## Purpose

## Summary of Changes

## Screenshot(s)

## Side Effects

## QA Notes

2022-07-11 19:44 UTC, adlius commented on lib/osf-components/addon/components/new-feature-popover/component.ts
> +import { tracked } from 'tracked-built-ins';
Should import from `@glimmer/tracking`

2022-07-11 19:56 UTC, brianjgeiger requested changes
Overall, nice and simple. 

We don't have a ticket for actually using this component. Should we put in the instantiation of it as part of this ticket and get it done with, or should we make a new ticket to actually use the component?

Does it check the cookie value in the instantiation rather than as part of the component itself? It might be easier for future usage if you could just bundle that all in as part of the component.

Could use a couple of component tests.

2022-07-11 20:03 UTC, futa-ikeda commented on lib/osf-components/addon/components/new-feature-popover/styles.scss
> +:global(.popover) {
We should add a local-class to this popover, since this will leak onto other usages of BsPopover.

2022-07-12 18:09 UTC, brianjgeiger approved these changes

2022-07-14 15:15 UTC, futa-ikeda commented on translations/en-us.yml
> +            outputFeaturePopoverBody: 'You can now add DOIs for external outputs (ex. data, code, papers, etc.) to your registration. Simply click Files and then select the new Outputs tab.'
Leaving a comment here so we remember to update this usage of `outputs` in case that language changes

2022-07-14 15:15 UTC, futa-ikeda approved these changes
🥠 🍪 ❗

2022-07-25 17:54 UTC, merged