[ENG-3949] Delete resource
CenterForOpenScience/ember-osf-web pull request #1598
Opened 2022-08-02 03:28 UTC by adlius

-   Ticket: [ENG-3949]
-   Feature flag: n/a

## Purpose

## Summary of Changes

## Screenshot(s)
 
![Screenshot from 2022-08-01 23-26-26](https://user-images.githubusercontent.com/1566880/182285505-7056ebd4-e640-4cca-ae95-61f008844564.png)
![Screenshot from 2022-08-01 23-26-33](https://user-images.githubusercontent.com/1566880/182285513-4810d1eb-f7e4-4953-a2fb-793cb3a3a97e.png)

## Side Effects

## QA Notes

2022-08-02 13:56 UTC, futa-ikeda requested changes
Should we use the `<DeleteButton>` component for this? If not, maybe we revisit the `<DeleteButton>` component after this project and turn it into a glimmer component?

2022-08-02 13:56 UTC, futa-ikeda commented on lib/osf-components/addon/components/resources-list/resource-card/template.hbs
> +                    <Button
This button needs an aria-label

2022-08-03 19:31 UTC, brianjgeiger requested changes
One additional thing that came up after a similar bug showed up elsewhere.

2022-08-03 19:31 UTC, brianjgeiger commented on lib/osf-components/addon/components/resources-list/delete-resource/component.ts
> +            this.toast.error(this.intl.t('osf-components.resources-list.delete_resource.delete_failure'));
This should show the error from the API. `this.toast.error(getApiErrorMessage(e), errorMessage);`

2022-08-03 19:59 UTC, brianjgeiger approved these changes

2022-08-03 21:31 UTC, futa-ikeda requested changes
2 minor things

2022-08-03 21:31 UTC, futa-ikeda commented on lib/osf-components/addon/components/resources-list/resource-card/template.hbs
> -                        aria-label={{t 'osf-components.resources-list.edit_resource.edit_button_aria_label'}}
Was this aria-label removed on purpose?

2022-08-03 21:31 UTC, futa-ikeda commented on lib/osf-components/addon/components/resources-list/resource-card/component.ts
> +    @service toast!: Toastr;
This seems unnecessary

2022-08-04 18:13 UTC, futa-ikeda approved these changes

2022-08-04 18:15 UTC, merged