Add resource bugfixes
CenterForOpenScience/ember-osf-web pull request #1609
Opened 2022-08-05 19:05 UTC by futa-ikeda

-   Ticket: []
-   Feature flag: n/a

## Purpose
- Address issues found with Add/Edit Resource modal
  - unfinalized resources weren't being deleted properly
  - User changes were persisting in an unintuitive way when editing an existing resource 

## Summary of Changes
- Remove "Preview" functionality when editing existing resource
- Delete unfinalized resource when adding a new resource
- Update tests

## Screenshot(s)

## Side Effects

## QA Notes

2022-08-05 19:55 UTC, brianjgeiger requested changes
Overall, it looks good. The only problem is that there is an error when saving from the edit view, at least in mirage. 

<img width="530" alt="Screen Shot 2022-08-05 at 3 15 16 PM" src="https://user-images.githubusercontent.com/6599111/183151095-fee6a714-bccd-424c-a54b-e86b73989424.png">

2022-08-08 12:41 UTC, brianjgeiger commented
Looking at this problem a bit more, the actual problem is that there's an exception being caught that isn't a jsonapi error, so it's not an array. The real exception is:

```
TypeError: curr is not a function
    at invokeWithArgs (queue.js:17:1)
    at queue.js:25:1
    at Proxy.reduce (<anonymous>)
    at queue.js:20:1
    at EditResourceModal.save (component.js:100:1)
    at save.next (<anonymous>)
    at Object.next (wait-for.js:78:1)
    at GeneratorState.step (generator-state.js:33:1)
    at TaskInstanceExecutor.generatorStep (executor.js:279:1)
    at TaskInstanceExecutor.handleResolvedContinueValue (executor.js:143:1)
```

2022-08-08 13:26 UTC, futa-ikeda commented
> Overall, it looks good. The only problem is that there is an error when saving from the edit view, at least in mirage.
> 
> <img alt="Screen Shot 2022-08-05 at 3 15 16 PM" width="530" src="https://user-images.githubusercontent.com/6599111/183151095-fee6a714-bccd-424c-a54b-e86b73989424.png">

Yea, this was luckily an easy fix `@reload` wasn't being passed in when editing an existing resource. Spent a little more time than I'd like to admit chasing that one down 😅

2022-08-08 13:27 UTC, brianjgeiger approved these changes
🎉 🐧 🎉

2022-08-08 13:43 UTC, merged