Add link to help docs
CenterForOpenScience/ember-osf-web pull request #1618
Opened 2022-08-11 18:48 UTC by futa-ikeda

-   Ticket: []
-   Feature flag: n/a

## Purpose
- Add link to help guides for resources
## Summary of Changes
- Add new link in the top of resources page
- Add new translation
- TODO: add this link to the leftnav when it is ready
## Screenshot(s)
![image](https://user-images.githubusercontent.com/51409893/184216285-5cb368d3-1c51-4a61-bedc-74b4fb911742.png)

## Side Effects

## QA Notes
- The helpdocs don't have a section for resources yet, but should before this feature is released

2022-08-11 18:53 UTC, brianjgeiger requested changes

2022-08-11 18:53 UTC, brianjgeiger commented on lib/osf-components/addon/components/resources-list/template.hbs
> +        >
Probably could use a data-test attribute in case QA wants to selenium test this.

2022-08-12 14:48 UTC, brianjgeiger approved these changes

2022-08-15 15:31 UTC, adlius approved these changes

2022-08-15 16:54 UTC, merged