Feature/a11y testimonial keyboard navigation
CenterForOpenScience/ember-osf-web pull request #1656
Opened 2022-09-12 14:09 UTC by chth0n1x

-   Ticket: https://openscience.atlassian.net/browse/ENG-3764
-   Feature flag: feature/a11y-testimonial-keyboard-navigation

## Purpose

The purpose of these changes was to make the OSF Researchers carousel component more accessible to users. This update included slight element redesign of the nested testimonial and carousel slide content and updating the corresponding aria-labels and CSS.

## Summary of Changes

	modified:   app/home/-components/testimonials/styles.scss
	modified:   app/home/-components/testimonials/template.hbs
	modified:   lib/osf-components/addon/components/carousel/styles.scss
	modified:   lib/osf-components/addon/components/carousel/template.hbs
	modified:   lib/osf-components/addon/components/carousel/x-header/template.hbs
	modified:   translations/en-us.yml

## Screenshot(s)

<img width="1632" alt="image" src="https://user-images.githubusercontent.com/82047646/189674732-89a4a1a4-aac3-4899-b25c-5ed2220aa4d5.png">
<img width="1632" alt="image" src="https://user-images.githubusercontent.com/82047646/189674478-22eb08f4-bb28-4315-a24f-c561716d9e3d.png">
<img width="1631" alt="image" src="https://user-images.githubusercontent.com/82047646/189674551-0b7c5e9d-46f0-40fb-b013-0735a5426aa0.png">
<img width="1633" alt="image" src="https://user-images.githubusercontent.com/82047646/189674624-8c75a9d0-caba-4c2b-ad33-b3911747d1bd.png">

## Side Effects

We will need to follow up with QA as I am currently testing the component locally on the Dashboard page. When the CSS is not properly set to an active state, this component has the ability to expand and obscure other component's text and elements. Thorough testing with more slides or differently queued active states for the buttons - both the top dot nav as well as left and right scroll arrows - will help ensure proper redirection of user focus.

## QA Notes

- Does the carousel display?
- Does only one slide display at a time?
- Are all three hard-coded slides present upon scroll? 
- Does the dot navigation properly correspond to the total number of slides? Will removing or adding slides update the dot navigation bar?
- Are each of the meaningful elements focusable by Tab? By Tab + Shift?
- Is the Voiceover/Screen Reader polite or does it interrupt the user experience?
- Is the keyboard directional flow a good user experience? Note: the number of tab depths into an element allows for symmetrical mirroring of controls similar to how we perceive them in the physical world. To ensure the experience was more seamless, left and right top tabs have been added that will also help indicate where on the slide the information is located with the aim of adding a right hand control.
- Is the contrast ratio good on all elements? Are there any that could improve?

2022-10-03 18:06 UTC, brianjgeiger requested changes
Let's bring this into modern ember practices with the `{{on}}` modifier, which is the big ask from this CR. Everything else is pretty minor.

2022-10-03 18:06 UTC, brianjgeiger commented on app/home/-components/testimonials/styles.scss
> +    font-family: 'Bree Serif';
You should generally have a fallback generic font-family in case the user doesn't have Bree Serif. For example, `font-family: 'Bree Serif' , serif;`

2022-10-03 18:06 UTC, brianjgeiger commented on app/home/-components/testimonials/styles.scss
> +    font-family: 'Bree Serif';
Same here with the generic font-family.

2022-10-03 18:06 UTC, brianjgeiger commented on app/home/-components/testimonials/styles.scss
> +        font-family: 'Open Sans';
Same here with the generic font family. `font-family: 'Open Sans', sans-serif;`

2022-11-03 17:48 UTC, closed without merging

2022-11-03 18:04 UTC, chth0n1x commented on app/home/-components/testimonials/component.ts
> +// import { action, computed } from '@ember/object';
Ok, this is now removed.