Initial set-up for extending mirage for collections
CenterForOpenScience/ember-osf-web pull request #1681
Opened 2022-10-21 17:00 UTC by bp-cos

This is set-up work for future collection moderation tickets.

2022-10-21 17:38 UTC, brianjgeiger requested changes
Just a couple of small things.

2022-10-21 17:38 UTC, brianjgeiger commented on mirage/scenarios/collections.ts
> +        id: 555,
Should this be a different id to the one above on L58?

2022-10-21 17:38 UTC, brianjgeiger commented on mirage/scenarios/collections.ts
> +    server.create('collected-metadatum', {
Didn't this get changed to 'collection-submission'?

2022-10-21 17:57 UTC, futa-ikeda requested changes
Just something very minor. It also looks like you'll need the latest changes from upstream feature/collections-moderation

2022-10-21 17:57 UTC, futa-ikeda commented on app/models/collection.ts
> +    @computed(`{${choicesFields?.join()}}?.length`)
I think checking the truthiness here is not needed

2022-10-21 17:57 UTC, futa-ikeda commented on app/models/collection.ts
> +        return choicesFields.filter(field => !!this[field]?.length );
Same here. No need to check for truthiness

2022-10-21 18:52 UTC, futa-ikeda approved these changes

2022-10-21 19:06 UTC, brianjgeiger approved these changes

2022-10-24 15:15 UTC, merged

2022-10-24 17:04 UTC, chth0n1x commented on app/models/collection.ts
> +        return choicesFields.filter(field => !!this[field].length );
@Brian, I believe a space has been added here. If that is intentional, it is okay. If not, we may want to remove this.

2022-10-24 17:05 UTC, chth0n1x commented on mirage/factories/collection-provider.ts
> +    } // eslint-disable-line semi
Also, are we able to remove the eslint-disable? It may cause tests to fail - is there a good reason to keep it?

2022-10-24 17:06 UTC, chth0n1x commented on mirage/factories/collection-provider.ts
> +    } // eslint-disable-line semi
Same here