[ENG-4113] Collections Moderator Management
CenterForOpenScience/ember-osf-web pull request #1689
Opened 2022-10-27 20:17 UTC by futa-ikeda

-   Ticket: [ENG-4113]
-   Feature flag: n/a

## Purpose
- Allow moderator management for collection-providers

## Summary of Changes
- Prevent issue on mobile view where provider-logo could flow out of header container on discover page
- Move moderator logic to provider-superclass
  - Move `moderators` relationship
  - Move `permissions` attribute
  - Move `currentUserCanReview` logic
- Check if the currentUser is actually a moderator to show "Moderation" button on navbar
- Tweak Moderator manager component to be less tied to registries implementation
- Use Moderator manager for collection-provider
- Tests + test selectors

## Screenshot(s)
- Admin view:
![image](https://user-images.githubusercontent.com/51409893/198387886-8384df7d-ea53-40a0-adb8-56dbe60047a9.png)
- Moderator view:
![image](https://user-images.githubusercontent.com/51409893/198389036-f48d9639-276f-494a-9fae-358640c8f5ec.png)

## Side Effects
- I don't think there will be any side-effects... 🤔 

## QA Notes
- Admins should be able to add moderators by user_id or by email
- Non-admin moderators should only be able to remove themselves

2022-10-28 15:28 UTC, brianjgeiger requested changes
The minorest of speed optimizations to make the test run a tiny bit faster.

2022-10-28 15:28 UTC, brianjgeiger commented on tests/engines/collections/acceptance/moderation/moderators-test.ts
> +        server.createList('moderator', 15, { provider });
Minor: this will run slightly faster if there are only 11 (10?) created moderators rather than 15 without affecting your test scenario.

2022-11-01 20:19 UTC, adlius reviewed
Overall looks pretty good. One question.

2022-11-01 20:19 UTC, adlius commented on mirage/views/moderator.ts
> +    }
Can we do `instanceof ModelInstance<MirageRegistrationProvider>` and/or `instance of ModelInstance<MirageCollectionProvider>` here to determine which provider we are getting? Or we could look at the url. I just don't like the fact that we are trying to assign `provider` to `schema.registrationProviders.find(parentID)` then reassign to something else afterwards depending on the request url.

2022-11-02 19:20 UTC, adlius approved these changes

2022-11-02 19:42 UTC, merged