[ENG-4159] Update make decision dropdown
CenterForOpenScience/ember-osf-web pull request #1693
Opened 2022-10-31 20:26 UTC by futa-ikeda

-   Ticket: [ENG-4159]
-   Feature flag: n/a

## Purpose
- Allow the make-decision-dropdown component to moderate collection-submissions

## Summary of Changes
- Move the make-decision-dropdown component out of registries engine
  - Move test files out of registries
  - Move translations out of registries

- [ ] Allow make-decision-dropdown to moderate collection-submissions
- [ ] Add tests for make-decision-dropdown
  - [ ] Tests for RegistrationRevisions workflow
  - [ ] Tests for CollectionSubmission workflow
  - [ ] Update existing test for Registration workflow to assure no CollectionSubmission or RegistrationRevision workflow stuff has leaked

## Screenshot(s)
- No visible changes for Registration and Revision update workflow

## Side Effects
- None

## QA Notes
- This PR has changes that _shouldn't_ change how the registration and revision moderation workflows function, but since some of the code for those workflows are being moved around, some regression testing in that area would be appreciated.

2022-11-08 16:19 UTC, brianjgeiger requested changes
Just a little refactoring requested in your newly combined component for readability.

2022-11-08 16:19 UTC, brianjgeiger commented on lib/osf-components/addon/components/make-decision-dropdown/component.ts
> +                };
This might be worth breaking into a function for better readability. The nesting gets a little deep here.

2022-11-08 16:19 UTC, brianjgeiger commented on lib/osf-components/addon/components/make-decision-dropdown/component.ts
> +            }
Same here with the nesting and the function.

2022-11-08 16:22 UTC, futa-ikeda commented on app/models/registration.ts
> +export type ActionableRegistrationStates = Exclude<RegistrationReviewStates, NonActionableRegistrationStates>;
Yea, Fabrice helped a lot with the TS work when we did registries moderation, so credit goes to him

2022-11-08 18:18 UTC, brianjgeiger approved these changes

2022-11-09 04:25 UTC, adlius commented
It looks good. However I am not super excited about extending the `make-decision-dropdown` component to cover cases for collection submissions, with the feat that it will slowly descend into the chaos of having too much conditionals in both the code and the template. I am okay with having this for now. But we need to think about what happens when we want to bring in preprint and preprint moderation.
Also, it seems we are also reusing the `review-action-list` component. Does it work with `collection-submission-actions` without any modification?

2022-11-11 16:18 UTC, adlius approved these changes

2022-11-14 20:48 UTC, merged