Added a test to verify that a moderator can self remove
CenterForOpenScience/ember-osf-web pull request #1741
Opened 2022-12-15 19:40 UTC by bp-cos

Coverage is at 100% for the controller. I was recently introduced to the value of adding BDD comments to TDD code for clarification.

Please take a look and see what you think.

Brian

2022-12-15 22:26 UTC, futa-ikeda requested changes
A few minor things, but overall, good test!

I'm a big fan of using the optional assert messages, so I like the addition of these behavior-related comments as a way to document expected behaviors a little further.

2022-12-15 22:26 UTC, futa-ikeda commented on lib/app-components/addon/components/branded-navbar/template.hbs
> +                                data-analytics-name='collection-moderation'
Just a bit of convention, for data-analytics-names, we usually use something like `data-analytics-name='Collection moderation'`

2022-12-15 22:26 UTC, futa-ikeda commented on lib/collections/addon/provider/moderation/template.hbs
> +                        data-analytics-name='collection-moderation-moderators-tab'
Similar convention here, something like `data-analytics-name='Collection moderation moderators tab'`

2022-12-15 22:26 UTC, futa-ikeda commented on tests/engines/collections/acceptance/moderation/moderators-remove-self-test.ts
> +    test('it removes a self collection moderator', async assert => {
```suggestion
    test('can remove self as a collection moderator', async assert => {
```

2022-12-15 22:26 UTC, futa-ikeda commented on tests/engines/collections/acceptance/moderation/moderators-remove-self-test.ts
> +        await visit(`/collections/${provider.id}/moderation/moderators`);
I think asserting that users get rerouted to the discover page after removing themselves as a moderator would be useful here too, just to document what the expected behavior should be

2022-12-16 20:16 UTC, futa-ikeda submitted a review, later dismissed
🧪

2022-12-16 20:17 UTC, futa-ikeda commented on tests/engines/collections/acceptance/moderation/moderators-remove-self-test.ts
> +        assert.equal(currentRouteName(), 'collections.discover', 'Users are rerouted to discover page.');
Ahh, it looks like this should be:

```suggestion
        assert.equal(currentRouteName(), 'collections.provider.discover', 'Users are rerouted to discover page.');
```

2022-12-16 21:49 UTC, futa-ikeda submitted a review, later dismissed
🧪 🧪

2022-12-20 18:30 UTC, futa-ikeda approved these changes

2022-12-20 18:33 UTC, merged

2022-12-28 16:37 UTC, chth0n1x reviewed
After the fact, but these changes look good. The test in particular is excellent, well done.