[ENG-4052] Added a new translation and conditional logic to display contributor adherence
CenterForOpenScience/ember-osf-web pull request #1748
Opened 2023-01-03 19:33 UTC by bp-cos

-   Ticket: [ENG-4052]
-   Feature flag: n/a

## Purpose

Updates requested by Mark to publicly show contributors take ownership.

## Summary of Changes

Add a new translation string. Then updated the logic differentiate between write permission and visibility

## Side Effects

None

## QA Notes

Verify that a user with write permissions sees the add icon, question mark and instructions on how to link a DOI and the adherence text.

Verify that a user without write permissions only sees the adherence text.

[ENG-4052]: https://openscience.atlassian.net/browse/ENG-4052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-01-03 19:36 UTC, brianjgeiger approved these changes

2023-01-04 16:34 UTC, brianjgeiger submitted a review, later dismissed

2023-01-04 20:48 UTC, futa-ikeda requested changes
It looks like the text is rendered like this if you are able to add resources to a registration. Some minor styling changes or wrapping the text in a `<p>` may be needed
![image](https://user-images.githubusercontent.com/51409893/210646200-d1c61c42-b165-4e9d-a1f3-ad16cd6e7deb.png)

2023-01-05 14:45 UTC, futa-ikeda submitted a review, later dismissed

2023-01-05 17:02 UTC, brianjgeiger approved these changes

2023-01-05 18:50 UTC, futa-ikeda approved these changes

2023-01-05 21:29 UTC, merged