[ENG-4291] Added the Dam registries to the registries landing page
CenterForOpenScience/ember-osf-web pull request #1766
Opened 2023-01-20 17:45 UTC by bp-cos

-   Ticket: [ENG-4291]
-   Feature flag: n/a

## Purpose

Add the dam registries logo to the registries splash page

## Summary of Changes

Added a logo

## Screenshot(s)
![Screenshot 2023-01-20 at 10 43 23 AM](https://user-images.githubusercontent.com/113387478/213769347-a2875e90-b80f-44a3-a382-530d1163c049.png)

![Screenshot 2023-01-20 at 10 43 19 AM](https://user-images.githubusercontent.com/113387478/213769374-bec69c86-373e-427f-8dad-5036c59b6e62.png)

## Side Effects

Moved the metascience logo down a row

## QA Notes

Verify the new logo, link and hover text

[ENG-4291]: https://openscience.atlassian.net/browse/ENG-4291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-01-20 18:30 UTC, futa-ikeda requested changes
Some minor things

2023-01-20 18:30 UTC, futa-ikeda commented on lib/registries/addon/components/registries-services-list/component.ts
>      @service analytics!: Analytics;
Looks like this component doesn't need the analytics service anymore either

2023-01-20 18:30 UTC, futa-ikeda commented on tests/integration/components/registries/registries-services-list/component-test.ts
> +                '/engines-dist/registries/assets/img/provider_logos/CharacterLab_logo-1794e99e73d6b8208ba3a8ba314a2e27.png',
I'm not sure if the `1794e99e73d6b8208ba3a8ba314a2e27` fingerprint ID is needed in this src reference? It seems odd that `ASIST_logo` before this didn't need it, but these ones after need it?

2023-01-20 19:05 UTC, futa-ikeda submitted a review, later dismissed

2023-01-31 19:42 UTC, chth0n1x submitted a review, later dismissed
@brianpilati this looks great, especially the test. Because this is a ticket for a branded registry and not the repo proper, I will hold my comment about local class selectors for a future PR but we can discuss it during next scrum as well.  Currently I am requesting changes for adding data test selectors to links as they are important elements to test. Great job and I look forward to re-reviewing your work.

2023-01-31 19:43 UTC, chth0n1x commented on lib/registries/addon/components/registries-services-list/template.hbs
> +                <a
A data test selector should be added here.

2023-01-31 19:43 UTC, chth0n1x commented on lib/registries/addon/components/registries-services-list/template.hbs
> +                    href='https://osf.io/registries/characterlabregistry'
And here.

2023-01-31 19:43 UTC, chth0n1x commented on lib/registries/addon/components/registries-services-list/template.hbs
> +                <a
And here.

2023-01-31 19:43 UTC, chth0n1x commented on lib/registries/addon/components/registries-services-list/template.hbs
> +                    href='https://osf.io/registries/egap'
And here.

2023-01-31 19:44 UTC, chth0n1x commented on lib/registries/addon/components/registries-services-list/template.hbs
> +                    href='https://osf.io/registries/metascience'
And here.

2023-01-31 19:45 UTC, chth0n1x commented on lib/registries/addon/components/registries-services-list/template.hbs
> +                    data-analytics-name='RWE - Registry'
And here.

2023-01-31 19:45 UTC, chth0n1x commented on lib/registries/addon/components/registries-services-list/template.hbs
> +                    data-analytics-name='YOUth - Registry'
And here.

2023-01-31 19:45 UTC, chth0n1x commented on lib/registries/addon/components/registries-services-list/template.hbs
> +                data-test-registries-list-contact-link
It's good here.

2023-02-02 21:46 UTC, futa-ikeda submitted a review, later dismissed

2023-02-03 13:44 UTC, brianjgeiger approved these changes

2023-02-03 20:31 UTC, futa-ikeda approved these changes

2023-02-03 20:38 UTC, merged