[ENG-2719] Added new translation strings for registries that are in the initial ReviewsState
CenterForOpenScience/ember-osf-web pull request #1773
Opened 2023-01-24 18:24 UTC by bp-cos

-   Ticket: [ENG-2719]
-   Feature flag: n/a

## Purpose

Added new translation strings for registries that are in the initial ReviewsState

## Summary of Changes

Three translations string were missing. These string were provided by the server.

## Screenshot(s)
![Screenshot 2023-01-24 at 11 06 43 AM](https://user-images.githubusercontent.com/113387478/214376268-e8ed62f9-42b8-4e28-926d-9d71bed287c8.png)
![Screenshot 2023-01-24 at 10 50 15 AM](https://user-images.githubusercontent.com/113387478/214376277-7e360c69-839c-44cb-91e3-f58f4280c50f.png)

## Side Effects

None

## QA Notes

The registry needs to be in an "initial" state.

[ENG-2719]: https://openscience.atlassian.net/browse/ENG-2719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-01-24 18:53 UTC, brianjgeiger approved these changes

2023-01-24 19:11 UTC, futa-ikeda requested changes
One small typo

2023-01-24 19:11 UTC, futa-ikeda commented on translations/en-us.yml
> +            long_description: 'This registration is awaiting approval by all admin contributors or after 48 hours has passes. An email will notify all registration contributors of the decision.
"after 48 hours has passed"

2023-01-24 19:30 UTC, brianjgeiger requested changes
One thing, if it's not a rabbit hole.

2023-01-24 19:30 UTC, brianjgeiger commented on translations/en-us.yml
> +            If the registration is pending after 48 hours has passed, contact support at support@osf.io.'
This should probably be the configured support email. Is that feasible to do without having to mess with a lot of structure for the generalized messages?

2023-01-25 19:12 UTC, brianjgeiger submitted a review, later dismissed

2023-01-31 18:16 UTC, futa-ikeda approved these changes

2023-01-31 19:50 UTC, chth0n1x commented on translations/en-us.yml
> +            short_description: 'Pending admin contributor approval'
Brian, I believe Admin should be either capitalized or spelled out fully as 'administrator'. This shorthand is slightly informal.

2023-01-31 19:51 UTC, chth0n1x approved these changes
These changes look good. I would like to see the spelling of Admin updated, but that is up to team input. Approving.

2023-02-02 15:57 UTC, merged