[ENG-3542] Percy 3.0 upgrade
CenterForOpenScience/ember-osf-web pull request #1794
Opened 2023-02-07 17:20 UTC by bp-cos

-   Ticket: [ENG-3542]
-   Feature flag: n/a

## Purpose

Upgrade Percy from 1.x to 3.0

## Summary of Changes

Ran the `$ npx @percy/migrate` script and followed the prompts and did not update imports.

## Side Effects

None

## QA Notes

No testing needed

[ENG-3542]: https://openscience.atlassian.net/browse/ENG-3542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-02-07 19:39 UTC, adlius commented on .github/workflows/CI.yml
> +        timeout-minutes: 10
```suggestion
```

2023-03-03 16:22 UTC, adlius approved these changes
Looks good! One question before merging.

2023-03-03 16:22 UTC, adlius commented on .github/workflows/CI.yml
> +      run: yarn percy exec --debug --parallel --verbose yarn test:ember --path ./dist --partition 1
Now that it seems to be working, do we still need the `--debug` flag?

2023-03-03 19:46 UTC, futa-ikeda requested changes
the changes to percy look good, but now that this is targeting the basket branch, I think we need to rebase `feature/percy-upgrade` onto `basket/antimony`

2023-03-07 14:22 UTC, adlius approved these changes

2023-03-15 15:51 UTC, futa-ikeda approved these changes
As per scrum discussions, we're ok with leaving the debug flag in for now. Hoping later conversations with Percy will give us a better idea why it breaks without it.

2023-03-15 18:57 UTC, merged