[ENG-4469] Add object filter and sort dropdown to search
CenterForOpenScience/ember-osf-web pull request #1864
Opened 2023-05-15 18:53 UTC by futa-ikeda

-   Ticket: [ENG-4469]
-   Feature flag: n/a

## Purpose
- Add object type filter and sort dropdown to search page

## Summary of Changes
- Add tabs to filter by object type (All, Projects, Registrations, Preprints, Files, Users)
- Add dropdown to sort results by Relevance, Date modified/created ascending and descending

## Screenshot(s)
- Desktop
![image](https://github.com/CenterForOpenScience/ember-osf-web/assets/51409893/0f75eca3-1f8c-46df-8b27-0ed66b0d8d6c)

- Mobile
![image](https://github.com/CenterForOpenScience/ember-osf-web/assets/51409893/83f81da1-d999-4781-a539-039a2b822ab9)

## Side Effects
- NA

## QA Notes

2023-05-15 19:03 UTC, brianjgeiger approved these changes

2023-05-22 17:56 UTC, brianjgeiger requested changes
Basically makes sense. Some of it is a little convoluted, but that's likely a necessity because of what you're trying to accomplish with the languages. Only thing I immediately saw was a `console.log` got left in.

2023-05-22 18:12 UTC, brianjgeiger approved these changes

2023-05-23 16:26 UTC, adlius approved these changes

2023-05-23 18:17 UTC, merged