[ENG-4488] Remove ember-cli-clipboard
CenterForOpenScience/ember-osf-web pull request #1910
Opened 2023-07-25 19:15 UTC by brianjgeiger

-   Ticket: [ENG-4488]
-   Feature flag: n/a

## Purpose

Ember-cli-clipboard was doing deprecated things, and upgrading it was a nightmare. The actual functionality is trivial to implement, though, so we've made our own version of its copy button.

## Summary of Changes

1. Add copy button
2. Add tests

## QA Notes

Test the copy button on the file detail page (hashes in the versions tab) and on the dev apps / tokens pages in all supported browsers, please.

2023-07-25 21:04 UTC, futa-ikeda requested changes
Just one line suggestion for me. Love everything else!

2023-07-25 21:04 UTC, futa-ikeda commented on lib/osf-components/addon/components/copy-button/component.ts
> +    @task
May not be needed now, but may want to pepper in a `@waitFor` here

2023-07-25 21:04 UTC, futa-ikeda commented on lib/osf-components/addon/components/copy-button/component.ts
> +        assert('clipboardText is a required parameter.', Boolean(this.args.clipboardText));
Yay asserts!

2023-07-25 21:04 UTC, futa-ikeda commented on tests/integration/components/copy-button/component-test.ts
> +        callback.withArgs('Error').throws();
Neat!

2023-07-26 04:22 UTC, adlius approved these changes

2023-07-26 13:44 UTC, futa-ikeda approved these changes

2023-07-26 14:02 UTC, merged