Update institution discover default query options
CenterForOpenScience/ember-osf-web pull request #1993
Opened 2023-09-08 20:42 UTC by futa-ikeda

-   Ticket: []
-   Feature flag: n/a

## Purpose
- Actual fetch stuff in the institution discover page

## Summary of Changes
- Add `rorIri` and `iri` attributes to Institution model (ultimately these comes from the `ror_uri ` and `identifier_domain` respectively in the admin app and is being added in a [BE PR](https://github.com/CenterForOpenScience/osf.io/pull/10452))
- fetch by either ROR, URI, or URL from OSFv2 URL (the URLs that are [relevant to SHARE for understanding institution affiliation](https://github.com/CenterForOpenScience/osf.io/blob/a3e0a0b9ddda5dd75fc8248d58f3bcdeece0323e/osf/metadata/osf_gathering.py#L811-L816))
- Fetch either by `affilation`, `creator,affiliation` (for preprints), `isContainedBy,affiliation` (for files)

## Screenshot(s)

## Side Effects

## QA Notes

2023-09-11 13:09 UTC, aaxelb reviewed
this'll need backend changes to work as desired, sorry to say

2023-09-11 14:45 UTC, futa-ikeda commented on app/institutions/discover/controller.ts
> +            'isContainedby,affiliation': identifiers,
Ahh, good catch, I had completely blanked that adding filters like this wasn't going to work! I agree with BrianG and also am in favor of using the comma-separated list of period-delimited paths. Will make those changes now.

2023-09-13 16:24 UTC, aaxelb requested changes
looks good, tho i think it'll need a few more changes to work with the change to `.`-delimited paths in query params

specifically: `RelatedPropertyPathModel.shortFormLabel` still joins on `,` -- may be best to remove that `shortFormLabel` getter and switch to `propertyPathKey` in the few places it's still used

2023-09-13 18:30 UTC, aaxelb approved these changes
🥦

2023-09-13 18:47 UTC, merged