[ENG-2224] "Edit Scopes" creates a new token
CenterForOpenScience/ember-osf-web pull request #2029
Opened 2023-10-12 14:16 UTC by chth0n1x

-   Ticket: https://openscience.atlassian.net/browse/ENG-2224
-   GitHub branch: access-token-go-to-list

## Purpose

The purpose of these changes is to have the access token value page close and redirect the user to the token list view upon clicking the 'Close' button.

## Summary of Changes

- The 'Edit scopes' button was updated to 'Close'
- The template file was updated to point to the correct translation string
- The refresh method was updated to transition the user to the token list view

## Screenshot(s)

<img width="1564" alt="Pasted Graphic 28" src="https://github.com/CenterForOpenScience/ember-osf-web/assets/82047646/21675305-20d5-4324-94d4-23448fe8781f">

## Side Effects

There should be no side effects.

## QA Notes

- Does the token value page close properly following clicking the 'Close' button
- Is the user redirected to the token list view?

2023-10-12 15:09 UTC, futa-ikeda requested changes
This avoids the problem, and I think it's a possible solution, but I think a proper fix to allow users to edit the token would be preferred. I left a comment in the [JIRA ticket](https://openscience.atlassian.net/browse/ENG-2224) explaining why. If you could have a crack at making the "Edit scopes" button work, that would be my preferred fix.

2023-10-12 15:13 UTC, brianjgeiger requested changes
While this is a potential workaround that could work, I think there's no reason to change the original workflow. So please continue working on being able to edit the scopes from after the token creation phase, or if that just won't work anymore for some reason, explain why it's infeasible. I can't think of a reason off the top of my head why the original workflow shouldn't be possible to achieve, but I'm not in the middle of the work so you may have found something I'm unaware of.

2023-10-12 15:23 UTC, chth0n1x commented
> This avoids the problem, and I think it's a possible solution, but I think a proper fix to allow users to edit the token would be preferred. I left a comment in the [JIRA ticket](https://openscience.atlassian.net/browse/ENG-2224) explaining why. If you could have a crack at making the "Edit scopes" button work, that would be my preferred fix.

@futa-ikeda this is the solution mentioned in the ticket, the decision made at scrum, and followed-up on. I had provided a solution here https://github.com/CenterForOpenScience/ember-osf-web/pull/2022 as well. This was the ticket for the solution you suggested. Let's meet to discuss it further.

2023-10-12 19:16 UTC, chth0n1x commented on app/settings/tokens/edit/controller.ts
>      refresh() {
Thank you, agreed.

2023-10-13 14:15 UTC, chth0n1x commented
> While this is a potential workaround that could work, I think there's no reason to change the original workflow. So please continue working on being able to edit the scopes from after the token creation phase, or if that just won't work anymore for some reason, explain why it's infeasible. I can't think of a reason off the top of my head why the original workflow shouldn't be possible to achieve, but I'm not in the middle of the work so you may have found something I'm unaware of.

Agreed, this solution was provided for the team if needed.

2023-10-13 14:15 UTC, closed without merging

2023-10-13 14:17 UTC, chth0n1x commented on app/settings/tokens/edit/controller.ts
>      refresh() {
Agreed, this has been updated now to refreshToken() in the codebase.