Added the fix for the search button per QA bug
CenterForOpenScience/ember-osf-web pull request #2044
Opened 2023-11-07 19:51 UTC by bp-cos

https://www.notion.so/cos/0de7c99478234fd7be57029dd96aa2d3?v=a4e6d7c70c004d27a0955aa2742775a4&p=8915343789724fc6bba353dd643bde80&pm=c

-   Ticket: [See Above]
-   Feature flag: n/a

## Purpose

The search button was not working on the new branded header

## Summary of Changes

Added a search button with sytling

## Screenshot(s)
![search button](https://github.com/CenterForOpenScience/ember-osf-web/assets/113387478/521354a4-47ea-4278-90ef-2162a690b80d)

## Side Effects

None

## QA Notes

Searching on the preprints page should now work by clicking the button and hitting enter

2023-11-07 21:54 UTC, futa-ikeda requested changes
Have you tried testing this fix locally? When I run it on my machine, it doesn’t seem to fix the issue mentioned in notion card. I think issue stems from the fact that we were trying to take users to a route that didn't exist, and we also need to tell the router which providerId to use for the discover page
If you update the `onSearch` action defined in `app/preprints/index/controller.ts` like this, hitting enter or clicking on the magnifying glass icon should route users to the search page correctly. The new button and style in this PR shouldn't be necessary
```
    @action
    onSearch(query: string) {
        let route = 'search';

        if (this.theme.isSubRoute) {
            route = 'preprints.discover';
        }

        this.router.transitionTo(route, this.theme.id, { queryParams: { q: query } });
    }
```

2023-11-08 14:35 UTC, futa-ikeda commented
The bug is for branded landing pages (https://staging3.osf.io/preprints/biohackrxiv), not the general OSF Preprints landing page

2023-11-08 20:11 UTC, futa-ikeda requested changes
I don't think we don't need the new button added here, as there is already the magnifying glass button to start searching, and users can also press the enter key to search

2023-11-08 21:49 UTC, futa-ikeda approved these changes

2023-11-09 15:33 UTC, adlius approved these changes

2023-11-09 16:02 UTC, merged