[ENG-5101] Add the ability to save and quasi-view a cedar record
CenterForOpenScience/ember-osf-web pull request #2106
Opened 2024-01-10 18:07 UTC by bp-cos

-   Ticket: [ENG-5101]
-   Feature flag: cedar

## Purpose

Add the ability to create and save a cedar record.

## Summary of Changes

Updates to existing files and extensive work in mirage.

## Screenshot(s)

N/A

## Side Effects

None

## QA Notes

Test away

[ENG-5101]: https://openscience.atlassian.net/browse/ENG-5101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-01-10 18:36 UTC, adlius requested changes
Some comments. Overall looks good.

2024-01-11 18:00 UTC, adlius commented on lib/osf-components/addon/components/cedar-metadata-editor/component.ts
>      instanceObject: any;
Indeed it was. When I wrote it I expect the whole component to just take in the JSON-LD blob as the `instanceObject` parameter. Now that it changes it makes sense to also change the name of the parameters.

2024-01-11 18:43 UTC, futa-ikeda commented on lib/osf-components/addon/components/cedar-metadata-editor/component.ts
> +            alert('this is for Futa - $5 - now saved');
Interesting. Why is try/catch a smell? Are there better mechanisms to let users know when saving has failed?

2024-01-11 19:22 UTC, futa-ikeda commented on app/guid-node/metadata/-components/metadata-tabs/template.hbs
> +            {{#each this.cedarMetadataRecords as |cedarMetadataRecord| }}
I was curious if we would ever run into a case where there would be no `tablist.tab` or `tab.tabPanel ` shown, but I realize that there will always be at least one of those shown, so we don't need to worry about `this. cedarMetadataRecords` being an empty list.

As an aside, it looks like [JSON API says for empty has-many relationships](https://jsonapi.org/format/#fetching-relationships), it should return a collection of length 0

2024-01-11 19:43 UTC, futa-ikeda approved these changes
💸

2024-01-12 16:45 UTC, merged