[ENG-4846] Add CEDAR widget to registrations
CenterForOpenScience/ember-osf-web pull request #2112
Opened 2024-01-22 18:07 UTC by bp-cos

-   Ticket: [ENG-4846]
-   Feature flag: local.js: registrations::full or registrations::lite

## Purpose

Add the CEDAR web component to registrations

## Summary of Changes

Moved 6 metadata components from app/guid-node/metadata/components into /lib/osf-components/addon/components/metadata

MIRAGE_SCENARIOS: [
     'registrations::full',
     'registrations::lite',
     'registrations::many-projects'
  ],

## Screenshot(s)
![Screenshot 2024-01-23 at 11 36 23 AM](https://github.com/CenterForOpenScience/ember-osf-web/assets/113387478/e45ab537-6bb0-45dc-90bf-a00875241e5c)

## Side Effects
Minimized the duplication of code

## QA Notes

[ENG-4846]: https://openscience.atlassian.net/browse/ENG-4846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-01-23 19:45 UTC, adlius requested changes
Some questions and suggestions.

2024-01-23 19:45 UTC, adlius commented on lib/registries/addon/overview/metadata/detail/route.ts
> +        }
I believe you may use `findIndex()` instead of `map()`.

2024-01-23 19:45 UTC, adlius commented on lib/registries/addon/routes.ts
> +            this.route('index', { path: '/'});
Do we really need an `index` route?

2024-01-24 02:36 UTC, adlius approved these changes
Approved. But one last minor thing.

2024-01-24 02:36 UTC, adlius commented on app/guid-node/metadata/add/controller.ts
> +    get getTabTitle(): string {
```suggestion
    get tabTitle(): string {
```

2024-01-24 02:36 UTC, adlius commented on app/guid-node/metadata/add/template.hbs
> +{{page-title this.getTabTitle}}
```suggestion
{{page-title this.tabTitle}}
```

2024-01-24 15:57 UTC, futa-ikeda approved these changes
Looks good to me! One leftover copy-paste artifact, but it's super minor

2024-01-24 15:57 UTC, futa-ikeda commented on mirage/scenarios/registrations.lite.ts
> + * @description Create the Beefs Registration
```suggestion
 * createDecafRegistration
 *
 * @description Create the decaf Registration
```

2024-01-24 16:12 UTC, merged