Added a share icon and fixed the routing to reflect the current tab
CenterForOpenScience/ember-osf-web pull request #2127
Opened 2024-02-05 18:35 UTC by bp-cos

-   Ticket: [https://www.notion.so/cos/Changing-tabs-does-not-change-the-URL-4edd6f28eb6746c888e0eb31dc50da4e]
-   Feature flag: n/a

## Purpose

When clicking on the tabs, the uri was not changing. Also add a share button

## Summary of Changes

Added some code to replace the browser history when the tab was clicked.

Also added a "share" icon to copy the current uri to the clipboard on projects and registrations.

I will add it to files, once I figure out the routing.

## Screenshots

![Screenshot 2024-02-05 at 11 33 54 AM](https://github.com/CenterForOpenScience/ember-osf-web/assets/113387478/c464cbf5-abc9-4e89-8872-3ecb13353123)

![Screenshot 2024-02-05 at 11 34 31 AM](https://github.com/CenterForOpenScience/ember-osf-web/assets/113387478/2120ce0a-d269-452e-950e-bb691528f564)

![Screenshot 2024-02-05 at 11 34 44 AM](https://github.com/CenterForOpenScience/ember-osf-web/assets/113387478/28907f6e-c994-43f4-883e-83bcbf3e480f)

## Side Effects

Numerous when messing around with the browser history

## QA Notes

Click on the tabs and the uri should change.

2024-02-05 21:57 UTC, adlius commented
Could you try using [Ember.js `Location` API ](https://api.emberjs.com/ember/release/classes/location/)to achieve this?

2024-02-05 21:57 UTC, adlius requested changes
Could you try using [Ember.js `Location` API ](https://api.emberjs.com/ember/release/classes/location/)to achieve this?

2024-02-06 15:51 UTC, futa-ikeda commented on lib/osf-components/addon/components/cedar-metadata-renderer/styles.scss
> +                color: #2d6a9f;
```suggestion
                color: $color-link-dark;
```

2024-02-06 17:22 UTC, futa-ikeda approved these changes
Approving for now. The `replaceHistory` is a bit of a smell, but I think addressing it would be non-trivial and possibly delay things at this stage. May be an easy fix if we use query-params for the active metadataRecord, but I haven't dug into the code to really tell.

2024-02-06 20:38 UTC, adlius approved these changes

2024-02-06 20:38 UTC, merged