[ENG-4888] Added the initial route, controller and template for the submit route
CenterForOpenScience/ember-osf-web pull request #2152
Opened 2024-02-27 18:34 UTC by bp-cos

-   Ticket: [ENG-4888]
-   Feature flag: n/a

## Purpose

Add the initial submit route and files

## Summary of Changes

Added the initial route, controller and template for the submit route

## Screenshot(s)
![Screenshot 2024-02-27 at 11 31 28 AM](https://github.com/CenterForOpenScience/ember-osf-web/assets/113387478/0df73122-639f-4973-82db-cf8a9292ac08)

## Side Effects

It's rather vanilla since a few items are just placeholders

## QA Notes

[ENG-4888]: https://openscience.atlassian.net/browse/ENG-4888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-02-27 18:41 UTC, futa-ikeda requested changes

2024-02-27 18:41 UTC, futa-ikeda commented on app/preprints/submit/route.ts
> +                isSearch: true,
```suggestion
```

2024-02-27 18:41 UTC, futa-ikeda commented on app/preprints/submit/route.ts
> +            this.router.transitionTo('not-found', `preprints/${args.provider_id}/discover`);
```suggestion
            this.router.transitionTo('not-found', `preprints/${args.provider_id}/submit`);
```

2024-02-27 21:35 UTC, cslzchen reviewed
Looks good and will approve after the two changes from Futa.

2024-02-28 15:21 UTC, cslzchen commented on app/preprints/submit/controller.ts
> +}
As @futa-ikeda mentioned, `is-mobile` is a builtin from `ember-responsive` now, so we don't need to wait for [his PR](https://github.com/CenterForOpenScience/ember-osf-web/pull/2153) to use `is-mobile` and remove this helper. We can do it here or use another PR to clean the code.

2024-02-28 16:26 UTC, cslzchen approved these changes
LGTM 🎆

2024-02-28 16:26 UTC, futa-ikeda approved these changes

2024-02-28 16:27 UTC, merged