ENG-4944 Added "withdrawn" to indexed preprint titles
CenterForOpenScience/ember-osf-web pull request #2161
Opened 2024-03-07 17:34 UTC by uditijmehta

-   Ticket: [ENG-4944](https://openscience.atlassian.net/browse/ENG-4944)
-   Feature flag: n/a

## Purpose

Add "Withdrawn" to indexed preprint titles

## Summary of Changes

Added getter that checks if the preprint title is withdrawn, added title entry for withdrawn preprints in yml file

## Screenshot(s)

![Screenshot 2024-03-07 at 12 32 51 PM (2)](https://github.com/CenterForOpenScience/ember-osf-web/assets/57388785/8907964c-25e7-4b3f-a117-91bf36f2d414)

## Side Effects

## QA Notes

2024-03-07 17:41 UTC, brianjgeiger commented
Drive by: This is looking good, but I think we will also need to alter the title in the Head Tags and the title bar of the window for this to be complete. Probably the ticket should have called this out explicitly.

2024-03-07 17:41 UTC, brianjgeiger commented
Also, well done on getting this to this point so quickly!

2024-03-07 18:27 UTC, futa-ikeda requested changes
Agree with what @brianjgeiger mentioned about updating some of the metadata we set on the page's head tag. This wasn't called out in the original ticket so I apologize for the bit of scope-creep here, but Google Scholar uses the metadata in the head tag to figure out titles. I believe there is a `setHeadTags` task on the `route.ts` file. If you could add some similar logic to update the title in there, that would be great. Very fast turn around on getting your first PR up as well! ⚡

2024-03-08 15:23 UTC, brianjgeiger requested changes
One suggestion to use the translated string in the `metaTagsData` and a couple of questions related to bumping the ember version.

2024-03-08 15:23 UTC, brianjgeiger commented on app/preprints/detail/route.ts
> +                title: preprint.isWithdrawn ? `Withdrawn: ${preprint.title}` : preprint.title,
Any reason not to use `this.intl.t` here?

2024-03-08 15:23 UTC, brianjgeiger commented on package.json
> +    "ember-source": "~3.28.12",
Is this the only thing that needs to change if we're bumping versions? Or are there other ember dependencies that also need to be updated?

Also, is this necessary for your PR, or would it make sense to do this as a separate PR so we can explore the above questions?

2024-03-08 16:19 UTC, brianjgeiger requested changes
It's verrry close. Need to re-yarn, and I think the logic on the title in the head tags is a little wrong. Other than that it looks great.

2024-03-08 16:19 UTC, brianjgeiger commented on yarn.lock
> +ember-source@~3.28.12:
Looks like you need to re-yarn as well.

2024-03-08 17:36 UTC, brianjgeiger approved these changes
🎉 🐧 🎉

2024-03-12 13:37 UTC, futa-ikeda approved these changes
Woohoo! Great work!

2024-03-12 14:29 UTC, merged