[ENG-6117] Add Filter for Orcid on Instutional Dashboard
CenterForOpenScience/ember-osf-web pull request #2315
Opened 2024-09-09 17:02 UTC by Johnetordoff

-   Ticket: [https://openscience.atlassian.net/browse/ENG-6117]
-   Feature flag: n/a

## Purpose

Add the ability to filter users by Orcid status, ensure filter works with sorting.

## Summary of Changes

- adds slider inputs to user institutional darshboard tab
- adds compontent code to make work
- adds template code for layout.

## Screenshot(s)
![Screenshot 2024-09-09 at 1 01 24 PM](https://github.com/user-attachments/assets/79ec3552-ddcd-4796-92bc-f9684d1b2b22)
![Screenshot 2024-09-09 at 1 01 19 PM](https://github.com/user-attachments/assets/c9c84a71-0472-4565-851e-7c8d030d1e25)

![Screenshot 2024-09-06 at 3 50 14 PM](https://github.com/user-attachments/assets/501756d5-d60d-4627-8505-a6a0f895965a)

## Side Effects

## QA Notes

2024-09-10 21:03 UTC, Johnetordoff commented on lib/osf-components/addon/components/sort-arrow/component.ts
> -        return this.args.sortBy || 'user_name';
Thought I'd just clean this up here.

2024-09-10 21:05 UTC, Johnetordoff commented on lib/osf-components/addon/components/sort-arrow/component.ts
> -        return this.args.sortBy || 'user_name';
I thought I'd just clean this up here in this PR.

2024-09-11 16:21 UTC, futa-ikeda requested changes
We're close! Just a couple of small things

2024-09-11 16:21 UTC, futa-ikeda commented on app/institutions/dashboard/-components/institutional-users-list/styles.scss
> +    display: none;
I believe doing `display: none` on an input will make it impossible to tab to, so I'd like to remove this property for accessibility sake.

2024-09-11 16:21 UTC, futa-ikeda commented on app/institutions/dashboard/-components/institutional-users-list/styles.scss
> +    position: relative;
If we remove `display: none` from the input as above, we'll have to likely change this to `position: absolute` and maybe remove `display: flex` so the slider goes over the input element

2024-09-11 16:21 UTC, futa-ikeda commented on app/institutions/dashboard/-components/institutional-users-list/styles.scss
> +    position: relative;
I think this will have to be `position: absolute` as well if the input is now shown

2024-09-11 16:21 UTC, futa-ikeda commented on app/institutions/dashboard/-components/institutional-users-list/template.hbs
> +                    <input type='checkbox' checked={{this.hasOrcid}} {{on 'change' (fn this.toggleOrcidFilter (not this.hasOrcid))}}>
The input doesn't have a valid label right now, so you will have to add `id='switches-container'` to the `<input>` element to associate the "Has ORCID" label to this input

2024-09-11 17:41 UTC, futa-ikeda approved these changes
🌟

2024-09-11 17:42 UTC, merged