Improve mobile styling inst dashboard
CenterForOpenScience/ember-osf-web pull request #2327
Opened 2024-09-13 18:05 UTC by Johnetordoff

-   Ticket: []
-   Feature flag: n/a

## Purpose

## Summary of Changes

## Screenshot(s)

## Side Effects

## QA Notes

2024-09-16 14:55 UTC, futa-ikeda requested changes
Just a couple minor changes. Could you add a screenshot for mobile view to the PR as well?

2024-09-16 14:55 UTC, futa-ikeda commented on app/institutions/dashboard/-components/institutional-users-list/template.hbs
> +            <label>{{t 'institutions.dashboard.users_list.total_users'}}</label>
`<label>` feels a bit inappropriate to use here, as there is no `<input>` that this is labelling. Could likely just be another `span` I think

2024-09-16 14:55 UTC, futa-ikeda commented on app/institutions/dashboard/-components/institutional-users-list/styles.scss
> +    color: #337ab7;
```suggestion
    color: $color-select;
```

2024-09-17 15:53 UTC, futa-ikeda approved these changes

2024-09-18 18:44 UTC, Johnetordoff commented
@Johnetordoff remember to close the hide/add dropdown on clicking `apply`

2024-09-19 14:52 UTC, Johnetordoff commented on app/institutions/dashboard/-components/total-count-kpi-wrapper/component-test.ts
> -            .hasText('20 OSF Public and Private Projects');
I'm not sure why this changed.

2024-09-20 17:35 UTC, futa-ikeda commented on app/institutions/dashboard/-components/institutional-users-list/styles.scss
> +@media (max-width: 1000px) {
We've tried to move away from hard-coding pixel values into our CSS. Instead, in the template you could use our `is-mobile` helper
```
<div local-class=table-wrapper {{if (is-mobile 'mobile'}}>
```
then change this line to be `.mobile` and adjust the nested selectors as needed

2024-09-20 17:35 UTC, futa-ikeda commented on app/institutions/dashboard/-components/institutional-users-list/styles.scss
> +        min-width: 1000px; /* Set the table's width to be wider than the viewport */
I worry about setting an explicit `min-width` here, as the table may not need the full 1000px as users can hide columns and whatnot... Can this be implemented without this hard-coded min-width?

2024-09-20 17:35 UTC, futa-ikeda commented on app/institutions/dashboard/-components/institutional-users-list/styles.scss
> +@media (max-width: 1000px) {
Actually, I think this scrolling behavior and no-wrap on the text is something we may want regardless of mobile or not. Let me doublecheck with product though

2024-09-20 19:11 UTC, futa-ikeda approved these changes
✨✨

2024-09-20 19:11 UTC, futa-ikeda commented on app/institutions/dashboard/-components/institutional-users-list/template.hbs
> +                        <Button @type='primary' {{on 'click' this.applyColumnSelection}} {{on 'click' dd.actions.close}}>
Just for future reference, if you want to have a click even do multiple actions in sequence, you can use either the `pipe` or `queue` helper like 
`{{on 'click' (queue this.firstAction this.secondAction)}}`

Docs for those can be found here: https://github.com/DockYard/ember-composable-helpers?tab=readme-ov-file#queue

2024-09-20 19:25 UTC, merged