[ENG-6669] Institutional Access project Request Modal
CenterForOpenScience/ember-osf-web pull request #2433
Opened 2024-12-17 20:48 UTC by Johnetordoff

-   Ticket: [https://openscience.atlassian.net/browse/ENG-6669]
-   Feature flag: n/a

## Purpose

## Summary of Changes

## Screenshot(s)

## Side Effects

## QA Notes

2024-12-18 14:19 UTC, Johnetordoff commented on app/institutions/dashboard/-components/object-list/contributors-field/component.ts
> +            const contributorId = contributor?.['@id']?.match(regex)?.[1] || '';
Is there a better way to get user guid?

2025-01-08 21:30 UTC, futa-ikeda requested changes
Looks good over all! Just some minor things here and there

2025-01-08 21:30 UTC, futa-ikeda commented on app/models/node-request.ts
> +  @belongsTo('node') node;
For these `belongsTo` relationships, we typically manually type them like
```suggestion
  @belongsTo('institution')
  institution!: AsyncBelongsTo<InstitutionModel> & InstitutionModel;
```
and so on with `import { AsyncBelongsTo } from '@ember-data/model';`

2025-01-08 21:30 UTC, futa-ikeda commented on translations/en-us.yml
> +              request_label: 'I am an admin associated with [institution] and I would like to be added to your project as a non-bibliographic contributor in order to assist with metadata curation ple
Looks like this should be `{institution}` instead of `[institution]`

2025-01-08 21:30 UTC, futa-ikeda commented on translations/en-us.yml
> +              open_aira_label: 'Open Project Request Modal Button'
Nit: I think it's `aria` instead of `aira`, but you're using the correct keys it seems, so nothing should break because of this

2025-01-09 12:47 UTC, Johnetordoff commented on app/institutions/dashboard/-components/object-list/component.ts
> +        setTimeout(() => {
Yes, I'll leave a comment here, I calarified this but only later on line 243, and not very well. The reason for the timeout is that ember bans having two dialogue modals open at the same time and the modal closing animation happens too slowly, so just 
```
modal1.close()
modal2.open()
```
opens modal2 before the modal1 close animation is complete. Causing the framework to produce an error because there are technically two open modals. Product wanted a modal on this, because the toast message is not enough.

2025-01-09 13:40 UTC, Johnetordoff commented on app/institutions/dashboard/-components/object-list/contributors-field/component.ts
> +                name: getSingleOsfmapValue(contributor, ['name']) || 'Unknown Contributor',
eh, actually this is from updating accidentally against the addon services branch (I think), but I will fix it to translate because it's coming anyway. Just a heads up.

2025-01-09 13:46 UTC, Johnetordoff commented on app/institutions/dashboard/-components/object-list/contributors-field/styles.scss
I keep having issues with Ember "Uppercase" component's css, especially `<Button>` button's need !important to override the no border rule, because (I believe) buttons had an accessibility requirement to have boarders at some point. I'll try to fix it, but I'll leave a long comment if I can't fix it.

2025-01-09 15:53 UTC, Johnetordoff commented on app/institutions/dashboard/-components/object-list/component.ts
> +        }
Yes this is because there isn't standardization of error messages, so some http response codes are in the payload and some are simply not there. the 429s and some 409s are not standard, however looking at this now and I think I can improve, so that it reads the response header instead of the payload.

2025-01-10 18:59 UTC, futa-ikeda requested changes
Just one translation key that I noticed. Looks good otherwise

2025-01-10 18:59 UTC, futa-ikeda commented on app/institutions/dashboard/-components/object-list/contributors-field/template.hbs
> +        aria-label={{t 'institutions.dashboard.request_project_message_modal.open_aira_label'}}
Looks like a leftover typo here
```suggestion
        aria-label={{t 'institutions.dashboard.request_project_message_modal.open_aria_label'}}
```

2025-01-10 18:59 UTC, futa-ikeda commented on translations/en-us.yml
> +              send_aira_label: 'Send Project Request Button'
Looks like these two translations aren't used, so good to remove them

2025-01-10 21:19 UTC, futa-ikeda approved these changes
🐍

2025-01-10 21:49 UTC, merged