[ENG-6744]
CenterForOpenScience/ember-osf-web pull request #2438
Opened 2024-12-26 15:39 UTC by opaduchak

… 

-   Ticket: [ENG-6744]
-   Feature flag: gravy_waffle

## Purpose

## Summary of Changes

- fixed configure button displayed when user won't be able to configure addon
- fixed user and resource reference reuest swarm

## Screenshot(s)

## Side Effects

## QA Notes

2024-12-27 16:13 UTC, adlius requested changes
Overall it looks really good. I have got one question. The ticket requires that the admin should be able to delete the addons that others have configured. So that means in the page after the "Configure" button is clicked, the pencil button should not be there. Does this PR remove the pencil buttons for admins when they try to configure addons that others have configured?
![Screenshot from 2024-12-27 10-45-11](https://github.com/user-attachments/assets/a2f0d436-747f-4428-aead-4d09e560851e)

2024-12-27 18:20 UTC, futa-ikeda reviewed
So the screenshot in this PR is from the perspective of someone who isn't a project admin, but is the owner of the connected Box and Google Drive account, correct?

2024-12-28 11:01 UTC, opaduchak commented
> So the screenshot in this PR is from the perspective of someone who isn't a project admin, but is the owner of the connected Box and Google Drive account, correct?

Yeah, you are right on the spot. Also, I've updated screenshot to include not already confgured addons

2024-12-30 21:44 UTC, adlius approved these changes

2024-12-30 21:44 UTC, merged